controller_joint_names: ['', 'left_shoulder_joint', 'left_pitch_joint', 'left_hip_joint', 'left_knee_joint', 'left_ankle_joint', 'right_shoulder_joint', 'right_pitch_joint', 'right_hip_joint', 'right_knee_joint', 'right_ankle_joint', ]
